spring:
  application:
    name: attendance
  devtools:
    restart:
      enabled: false
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
      enabled: true

# 파일 업로드 저장 경로
file:
  upload:
    dir: ./data/userlist

# 출석 로그 파일 저장 경로
attendance:
  log:
    dir: ./data/attendance
    excel: ./data/attendance/무료급식 일일 식사내역_26.8_일지.xlsx
    sheets: 내역1,내역2

logging:
  level:
    com.bgrc.attendance: info
